# This file is automatically generated from remake_models.yml.whisker:
# edit the file there (or the files that it includes).

remake::create_bindings()
iter <- 10

# Model: 1---------------------
## Effect: constant
run_single_stan_chain(make_stan_model(get_chunks_model1_constant()), stan_data,chain_id=1, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model1_constant()), stan_data,chain_id=2, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model1_constant()), stan_data,chain_id=3, iter=iter)
## Effect: trait
run_single_stan_chain(make_stan_model(get_chunks_model1_trait()), stan_data,chain_id=1, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model1_trait()), stan_data,chain_id=2, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model1_trait()), stan_data,chain_id=3, iter=iter)
## Effect: species
run_single_stan_chain(make_stan_model(get_chunks_model1_species()), stan_data,chain_id=1, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model1_species()), stan_data,chain_id=2, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model1_species()), stan_data,chain_id=3, iter=iter)
## Effect: trait_species
run_single_stan_chain(make_stan_model(get_chunks_model1_trait_species()), stan_data,chain_id=1, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model1_trait_species()), stan_data,chain_id=2, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model1_trait_species()), stan_data,chain_id=3, iter=iter)

# Model: 2---------------------
## Effect: constant
run_single_stan_chain(make_stan_model(get_chunks_model2_constant()), stan_data,chain_id=1, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model2_constant()), stan_data,chain_id=2, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model2_constant()), stan_data,chain_id=3, iter=iter)
## Effect: trait
run_single_stan_chain(make_stan_model(get_chunks_model2_trait()), stan_data,chain_id=1, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model2_trait()), stan_data,chain_id=2, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model2_trait()), stan_data,chain_id=3, iter=iter)
## Effect: species
run_single_stan_chain(make_stan_model(get_chunks_model2_species()), stan_data,chain_id=1, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model2_species()), stan_data,chain_id=2, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model2_species()), stan_data,chain_id=3, iter=iter)
## Effect: trait_species
run_single_stan_chain(make_stan_model(get_chunks_model2_trait_species()), stan_data,chain_id=1, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model2_trait_species()), stan_data,chain_id=2, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model2_trait_species()), stan_data,chain_id=3, iter=iter)

# Model: 3---------------------
## Effect: constant
run_single_stan_chain(make_stan_model(get_chunks_model3_constant()), stan_data,chain_id=1, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model3_constant()), stan_data,chain_id=2, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model3_constant()), stan_data,chain_id=3, iter=iter)
## Effect: trait
run_single_stan_chain(make_stan_model(get_chunks_model3_trait()), stan_data,chain_id=1, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model3_trait()), stan_data,chain_id=2, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model3_trait()), stan_data,chain_id=3, iter=iter)
## Effect: species
run_single_stan_chain(make_stan_model(get_chunks_model3_species()), stan_data,chain_id=1, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model3_species()), stan_data,chain_id=2, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model3_species()), stan_data,chain_id=3, iter=iter)
## Effect: trait_species
run_single_stan_chain(make_stan_model(get_chunks_model3_trait_species()), stan_data,chain_id=1, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model3_trait_species()), stan_data,chain_id=2, iter=iter)
run_single_stan_chain(make_stan_model(get_chunks_model3_trait_species()), stan_data,chain_id=3, iter=iter)


