---
title: "Literature notes"
author: "J Camac"
date: "22 October 2014"
output: html_document
---
## DROUGHT
**Reference**
Sterck, F. J., Martínez-Vilalta, J., Mencuccini, M., Cochard, H., Gerrits, P., Zweifel, R., et al. (2012). Understanding trait interactions and their impacts on growth in Scots pine branches across Europe. Functional Ecology, 26(2), 541–549. doi:10.1111/j.1365-2435.2012.01963.x

*Findings*
- Tracheid hydraulic diameter was the best predictor of cavitation vulnerability
- Leaf area to sapwood area ratio was positively correlated with branch growth and tracheid hydraulic diameter (thus caviatation vulnerability)
- Wood density decreased cavitation vulnerability, while it increased with double cell wall thickness & tracheid diameter
- Cause & effect analysis (pathway analysis) suggested the causal link affecting caviation vulnerability and specific conductivity was tracheid hydraulic diameter and not other anatomical traits such as wood density and double cell wall thickness.
- Pathway analysis also suggested that growth was only driven by leaf area to sapwood ratio.

*Other*
-intraspecific variation to demonstrate functional trade-offs is superior to, or at least as valuable as, the use of interspecific variation.

**Reference**
Poorter, L., & Markesteijn, L. (2008). Seedling traits determine drought tolerance of tropical tree species. Biotropica, 40(3), 321–331. doi:10.1111/j.1744-74.29007.00380.x

*Findings*
- Dry forest species tended to have compound leaves,high stem dry matter content(stem dry mass/fresh mass),and low leaf area ratio,suggesting that reduction of transpiration and avoidance of xylem cavitation are important for their success
- Deciduous species had longer survival times than evergreens (because they could effectively shut down)
- When assessing only evergreens Wood density (stem density) was postively correlated with drought tolerance.
- Drought survival was mainly determined by deciduousness & presence of taproot. Both factors explained 74% of the survival variation. wood density.
- Trait relationships with drought tolerance: Leaf are ratio (-), Leaf mass fraction(-), Root mass fraction (+; i.e. large roots can act as storage), Stem dry matter content (+).

- Three functional groups appear to exist:
  - Drought avoiders (deciduous plants, taproots)
  - Drought resisters (high dry matter content in leaves & stem)
  - light-demanding moist forest species with high belowground foraging capacity
  
*Other*
- "The seedling stage is generally considered to be the most important bottleneck for successful regeneration in dry areas, as seedlings, with their limited root system are most vulnerable to drought."

- "Dry adapted species have lower tranpiring leaf area per unit plant mass and have compound leaves."
- "Small leaflets have a lower boundary layer resistance, which allows for better convective cooling of leaves."
- Rooting depth could also be associated with increased tolerance as deeper soil layers have more water.
- "Xylem caviation is generally considered to be the most important cause of tree mortality in dry habitats"

## Light

**Reference**

Poorter, L., Bongers, L., & Bongers, F. (2006). Architecture of 54 moist-forest tree species: traits, trade-offs, and functional groups. Ecology, 87(5), 1289–1301.

*Findings*
1) Crown area increased strongly, and nonlinearly, with tree height; Crown length increased monotonically with tree height
2) Light demand was a stronger predictor of architecture than Hmax. The strength of these relationships changed with ontogeny with light strength increasing with size.

- Stem height was positively related to Hmax at larger reference diameters. 
- Wood density was not related to Hmax (contrary to expectations)
- Height was positively correlated with crown area (non-linear) and crown length (linear)
- Asymptotic height growth was not found in all species (these tended to be small understorey species)


## Drought & Shade tolerance

**Reference**
Sterck, F., Markesteijn, L., & Schieving, F. (2011). Functional traits determine trade-offs and niches in a tropical forest community. Proceedings of the National Academy of Sciences of the United States of America.

*Findings*
- Aquisitive species would do better then conservative species under high light & water conditions but do worse under low light & water conditions. (supported)

*Suggested mechanism*
Acquisitive species are characterized by higher levels of photosynthetic proteins (such as Rubisco) than conservative species; have higher carbon gain rates than conservative species when light is not limiting, have protein-driven high respiration rate at low light levels.

- Under dry conditions aquisitive species are expected to close their stomata and reduce transpiration to avoid hydraulic failure, which creates a risk to starve from carbon deficiency when photosynthesis goes too far down. This is because such species require a higher hydraulic conductivity to sustain high transpiration rates. Such highly conductive wood, however, involves a higher risk of hydraulic failure.


*Other information*
"neutral theory advocates that coexisting species tend to be selected for the most common environmental conditions and, therefore, that most coexisting species are functionally equivalent and share similar niches"



**Reference**
Cavaleri, M. A., Oberbauer, S. F., Clark, D. B., Clark, D. A., & Ryan, M. G. (2010). Height is more important than light in determining leaf morphology in a tropical forest. Ecology, 91(6), 1730–1739.

*Findings*
- LMA linearly increased with height for all species pooled and for each functional group individually (except epiphytes), possibly through the influence of gravity on leaf water potential and turgor pressure.
- Light was also positively correlated with LMA... however this was mainly at light levels < 20% TRANS

*Suggested mechanisms*
- Xylem water potential decreases by 0.01 MPa per m of height simply because of gravity, as such leaf turgor pressure is lower at higher heights. This means that cells are small and thus can be packed more denesly causing an increase in cell wall per given area.

*Other*
"A kg of leaves at the bottom of a canopy generally has three to five times the surface area of the same mass of leaves at the top of the canopy"


**Reference**
Markesteijn, L., Poorter, L., Bongers, F., Paz, H., & Sack, L. (2011). Hydraulics and life history of tropical dry forest tree species: coordination of species’ drought and shade tolerance. New Phytologist, 191(2), 480–495. doi:10.1111/j.1469-8137.2011.03708.x

*Findings*
- Leaf hydraulic conductivity was negatively correlated with drought tolerance
- Pioneer species and deciduous species have higher hydraulic efficiency than shade tolerant and evergreen species.
- Stem hydraulic conductivity was negatively associated with wood density and positively correlated with maximum vessel length (reflecting a trade-off between hydraulic saftey vs efficiency)
- drought and shade tolerance scaled similarly with hydraulic properties (-), wood density (+) & leaf dry matter content (+).

*Suggested mechanism*
- Stem hydraulic conducitivity was be negatively associated with both shade and drought tolerances, because light-demanding species have higher photosynthetic capacity, increased transpiration and higher leaf water demand and thus are more sensitive to caviatation than shade-tolerant species.


**Reference**
Markesteijn, L., & Poorter, L. (2009). Seedling root morphology and biomass allocation of 62 tropical tree species in relation to drought- and shade-tolerance. Journal of Ecology, 97(2), 311–325. doi:10.1111/j.1365-2745.2008.01466.x

*Findings*
- Seedlings of dry forest species improve water foraging capacity in deep soil layers by an increased below-ground biomass allocation and by having deep roots. They minimize the risk of cavitation by making dense stems, and reduce transpiration by producing less leaf tissue. 
- Moist forest seedlings have large leaf areas and a greater above-ground biomass, to maximize light interception, and long, cheap, branched root systems, to increase water and nutrient capture.
- Found no trade-off between shade and drought tolerance as they are thought to depend on different morphological adaptations. High biomass investment into root system for drought tolerance and shade tolerance by low growth rate and low SLA (this latter point is odd... as more persistent organs will result in slower growth rates... so if anything they are correlated.)

-three major drought strategies: 
(i) evergreen drought-tolerant species have high biomass investment in enduring organs, minimize cavitation and minimize transpiration to persist under dry conditions; 
(ii) drought-avoiding species maximize resource capture during a limited growing season and then avoid stress with a deciduous leaf habit in the dry season; 
(iii) drought-intolerant species maximize both below- and above-ground resource capture to increase competitiveness for light, but are consequently precluded from dry habitats.

*Other*
"Species are most susceptible to drought in the early phase of their life cycle when seedlings have limited access to water as their small root systems is confined to the upper soil layers"
"Seedling mortality rates increase exponentially with a decrease in rainfall, as such seedling size at the onset of the dry season is therefore important"

"Meta-analysis of 806 woody species from the northern hemisphere suggested a negative relationship between drought- and shade- tolerance (Niinemets & Valladares 2006)."

"The functional equilibrium hypothesis suggests under a given regime of stress, plants maximise their suface area for intake of the most limiting resource. (Brouwer 1963)"