#!/usr/bin/env Rscript

## Script removes extra lines,
## Changes bibkey to authjor_titlte_year

## Mostly a big hack work around (bibtex entry
## redefines '[' and/or '[[' in ways that cause nothing but grief)

args <- commandArgs(TRUE)[1]

library(bibtex)

last <- function(x){
	x[[length(x)]]
}

new_bib_key <- function(bib) {
	bib_plain <- unclass(bib)

	author <- last(strsplit(as.character(bib$author[[1]])," ")[[1]])
	title <- tolower(strsplit(gsub("{", "", as.character(bib$title), fixed=TRUE), " ")[[1]])
	i <- 1
	while(length(title) >1 & title[1] %in% c("the", "a", "or")){
		title <- title[-c(1)]
	}
	tolower(paste(author, title[1], bib$year, sep="_"))
}

bib <- readLines(args)

# Remove unneeded lines

for(s in c("file =","lccn = ","issn =", "shorttitle =", "month = ", "urldate =", "date-added =", "date-modified =", "bdsk-url-", "language = ", "PMID:") ) {
	remove <- grep(s, bib, fixed=TRUE)
	if(length(remove) > 0)
		bib <- bib[-c(remove)]
}

# change keys
old_keys <- sapply(read.bib(args), function(x) x$key)
new_keys <- sapply(read.bib(args), new_bib_key)

for(i in seq_along(old_keys)) {
	bib <- gsub(old_keys[i], new_keys[i], bib)
}

writeLines(bib, args)

# Print in sorted order
bib_all <- read.bib(args)
keys <- sort(sapply(bib_all, function(x) x$key))
write.bib(bib_all[[keys]], file = args)
